name: simplewebrtc_flutter_webrtc_shim
description: Flutter WebRTC plugin for iOS/Android.
version: 0.2.7
homepage: https://simplewebrtc.com

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.simplewebrtc.webrtc
        pluginClass: FlutterWebRTCPlugin
      ios:
        pluginClass: FlutterWebRTCPlugin

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ^1.10.0
